// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exposure() {
  return window['go']['main']['App']['Exposure']();
}

export function ResetCalibration() {
  return window['go']['main']['App']['ResetCalibration']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetCalibration(arg1) {
  return window['go']['main']['App']['SetCalibration'](arg1);
}

export function SetCeiling(arg1) {
  return window['go']['main']['App']['SetCeiling'](arg1);
}

export function SetLimiterEnabled(arg1) {
  return window['go']['main']['App']['SetLimiterEnabled'](arg1);
}

export function SetTargetSPL(arg1) {
  return window['go']['main']['App']['SetTargetSPL'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
