// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';
import {service} from '../models';

export function Exposure():Promise<domain.ExposureSummary>;

export function ResetCalibration():Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetCalibration(arg1:number):Promise<void>;

export function SetCeiling(arg1:number):Promise<void>;

export function SetLimiterEnabled(arg1:boolean):Promise<void>;

export function SetTargetSPL(arg1:number):Promise<void>;

export function Settings():Promise<main.SettingsView>;

export function Status():Promise<service.Status>;
